# Copie este arquivo para .streamlit/secrets.toml e ajuste se precisar.
# O secrets.toml NÃO deve ser versionado (já está no .gitignore).
MONGO_URI = "mongodb://localhost:27017"
MONGO_DB_NAME = "openf1_data"
